buy/urls.py
from django.conf.urls import url
from buy.views import retail_outlet_as_csv, article_27_as_csv


urlpatterns = [
    url(r'^retail-outlets/$', retail_outlet_as_csv, name='retail-outlets-as-csv'),
    url(r'^article-27/$', article_27_as_csv, name='article-27-as-csv'),
]

collaborate/urls.py
from django.conf.urls import url
from .views import ArticleProposalSimpleView, ArticleProposalView, ArticleProposalThanksView, ArticleProposalListView, ArticleProposalDetailView


urlpatterns = [
    url(r'^$', ArticleProposalView.as_view(), name='article-proposal'),
    url(r'^simple/$', ArticleProposalSimpleView.as_view(), name='article-proposal-simple'),
    url(r'^merci/$', ArticleProposalThanksView.as_view(), name='article-proposal-thanks'),
    url(r'^propositions/$', ArticleProposalListView.as_view(), name='article-proposal-list'),
    url(r'^propositions/(?P<pk>\d+)/$', ArticleProposalDetailView.as_view(), name='article-proposal-detail'),
]

medor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from cms.sitemaps import CMSSitemap
from django.contrib.sitemaps.views import sitemap


admin.autodiscover() # Not required for Django 1.7.x+


urlpatterns = [
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}),
]


urlpatterns = i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^filer/', include('filer.urls')),
    url(r'^subscribe/', include('subscribe.urls')),
    url(r'^buy/', include('buy.urls')),
    url(r'^', include('publish.urls')),
    url(r'^', include('cms.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscribe/urls.py
from django.conf.urls import url
from subscribe.views import JadoreView


urlpatterns = [
    url(r'^jadore/$', JadoreView.as_view(), name='jadore'),
]

collaborate/models.py
# -*- coding: utf-8 -*-
from django.db import models
import markdown
from markdown.extensions.toc import TocExtension
from django.utils.text import Truncator


SECTION_CHOICES = (
    (0, u'Enquête'),
    (1, u'Portrait ou récit'),
    (2, u'Interview'),
    (3, u'Portfolio photo'),
    (4, u'Autre')
)


class ArticleProposal(models.Model):
    creation_date = models.DateTimeField(
        auto_now_add=True
    )
    name = models.CharField(
        max_length=50,
        verbose_name="Nom"
    )
    email = models.EmailField(
        max_length=75,
        verbose_name="Courriel"
    )
    phone = models.CharField(
        max_length=50,
        blank=True,
        verbose_name="Téléphone"
    )
    twitter_account = models.CharField(
        max_length=100,
        blank=True,
        verbose_name="Compte Twitter"
    )
    address = models.TextField(
        verbose_name="Adresse"
    )
    subject_title = models.CharField(
        max_length=300,
        verbose_name="Titre",
        help_text="Donnez un titre à votre proposition"
    )
    section = models.PositiveSmallIntegerField(
        choices=SECTION_CHOICES,
        default=0,
        verbose_name="Rubrique concernée (a priori)",
        help_text="Destinez-vous votre sujet à une rubrique précise ?"
    )
    abstract = models.CharField(
        max_length=750,
        verbose_name="Résumé",
        help_text="Rédigez comme s’il s’agissait d’un chapeau destiné à un média généraliste.",
        blank=True
    )
    is_urgent = models.BooleanField(
        default=False,
        verbose_name="Urgence",
        help_text="Votre sujet nécessite-t-il une publication rapide sur le web ou sur papier (pour préserver l'exclusivité par exemple) ?"
    )
    body = models.TextField(
        verbose_name="Contenu",
        blank=True,
        help_text="Présentez-vous et présentez-nous votre sujet : de quoi s’agit-il, où en êtes-vous dans vos recherches, quelles sont vos pistes et hypothèses, en quoi ce sujet est-il inédit, sous quelle forme l’imaginez-vous, etc. ?"
    )
    is_answered = models.BooleanField(
        default=False,
        verbose_name=u"Répondu?",
    )
    comment = models.TextField(
        verbose_name=u"Commentaire",
        blank=True,
        help_text=u"On lui a dit quoi?"
    )

    class Meta:
        verbose_name = "Proposition d'article"
        verbose_name_plural = "Propositions d'articles"
        ordering = ['-creation_date']

    def __unicode__(self):
        return self.subject_title

    @models.permalink
    def get_absolute_url(self):
        return ('article-proposal-detail', (), {'pk': self.pk})

    @property
    def body_as_html(self):
        md = markdown.Markdown(output_format="html5", extensions=['extra', TocExtension(baselevel=2)])
        return md.convert(self.body)

    @property
    def short_title(self):
        return Truncator(self.subject_title).chars(50)

collaborate/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import ArticleProposal


class ArticleProposalForm(forms.ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    class Meta:
        model = ArticleProposal
        fields = [
            'name',
            'email',
            'phone',
            'twitter_account',
            'address',
            'subject_title',
            'body'
        ]

        widgets = {
            'address': forms.Textarea(attrs={'rows': 5, 'cols': ''}),
        }


class ArticleProposalSimpleForm(forms.ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    class Meta:
        model = ArticleProposal
        fields = [
            'name',
            'email',
            'phone',
            'address',
            'subject_title',
            'body'
        ]

        widgets = {
            'address': forms.Textarea(attrs={'rows':5, 'cols': ''}),
        }

collaborate/views.py
from django.template.loader import render_to_string
from django.views.generic.edit import FormView
from django.views.generic import ListView, DetailView
from .forms import ArticleProposalForm, ArticleProposalSimpleForm
from .models import ArticleProposal
from django.core import urlresolvers
from django.core.mail import send_mail
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.contrib.sites.shortcuts import get_current_site


class ArticleProposalThanksView(TemplateView):
    template_name = "collaborate/article_proposal_thanks.html"


class ArticleProposalBaseView(FormView):
    success_url = reverse_lazy('article-proposal-thanks')

    def form_valid(self, form):
        form.save()
        obj = form.instance
        site = get_current_site(self.request)
        admin_url = u"https://%s%s" % (site, urlresolvers.reverse('admin:collaborate_articleproposal_change', args=(obj.id,)))

        subject = "Nouvelle demande de collaboration"
        message = render_to_string('collaborate/article_proposal_alert.txt', {'obj': obj, 'admin_url': admin_url})
        sender = "jaiuntrucpourvous@medor.coop"
        recipients = ["jaiuntrucpourvous@medor.coop"]
        send_mail(subject, message, sender, recipients)

        subject = "Demande de collaboration"
        message = render_to_string('collaborate/article_proposal_confirmation.txt', {'obj': obj})
        sender = "jaiuntrucpourvous@medor.coop"
        recipients = [obj.email]
        send_mail(subject, message, sender, recipients)

        return super(ArticleProposalBaseView, self).form_valid(form)


class ArticleProposalView(ArticleProposalBaseView):
    template_name = 'collaborate/article_proposal.html'
    form_class = ArticleProposalForm


class ArticleProposalSimpleView(ArticleProposalBaseView):
    template_name = 'collaborate/article_proposal_simple.html'
    form_class = ArticleProposalSimpleForm


def can_read_proposals(user):
    """docstring for can_read_proposals"""
    return user.groups.filter(name='Collaboration').exists()


class ArticleProposalListView(ListView):
    model = ArticleProposal

    @method_decorator(user_passes_test(can_read_proposals))
    def dispatch(self, *args, **kwargs):
        return super(ArticleProposalListView, self).dispatch(*args, **kwargs)

class ArticleProposalDetailView(DetailView):
    model = ArticleProposal

    @method_decorator(user_passes_test(can_read_proposals))
    def dispatch(self, *args, **kwargs):
        return super(ArticleProposalDetailView, self).dispatch(*args, **kwargs)

collaborate/templates/collaborate/article_proposal.html
{% extends "subscribe/base_forms.html" %}
{% load i18n collaborate_tags %}

{% block id %}collaborating{% endblock %}

{% block content %}
    <div id="steps">
        <div class="active" style="margin:auto 15% !important; margin-top:15px !important;">Proposer un sujet</div>

        <p class="intro-collaborate">Médor est à la recherche de sujets
        journalistiques inédits. Si vous êtes auteur (journaliste, photographe,
        illustrateur, bédéiste…) et que avez une proposition qui colle avec nos
        objectifs (profitez-en pour <a href="/magazine">aller vérifier ici</a>), remplissez ce formulaire. Médor s’engage à
        respecter la confidentialité de ces propositions.</p>

        <p class="intro-collaborate">Si vous n’êtes pas professionnel du
        journalisme mais que vous avez une information, une idée ou une piste à
        nous soumettre, utilisez <a href="{% url 'article-proposal-simple' %}">le formulaire simplifié</a>.</p>

        <p class="intro-collaborate">Nous analyserons chaque proposition avec
        l’attention qu’elle mérite. Mais soyons honnêtes&thinsp;: nous sommes parfois
        débordés et il se peut que nous tardions à vous répondre.</p>

        <p class="intro-collaborate">Merci pour votre intérêt&thinsp;!</p>

        <!-- <p class="intro-collaborate">Médor -->
        <!-- est à la recherche de sujets journalistiques inédits, principalement -->
        <!-- d’enquêtes, qui questionnent le fonctionnement de la Belgique et le -->
        <!-- monde dans lequel on vit. Ils peuvent couvrir tous les champs de la vie -->
        <!-- en société (politique, économie, sports, média, culture, société...) et -->
        <!-- prendre des formes diverses (texte, photos, BD, collage,...). Nous ne -->
        <!-- publions pas de textes de fiction et rémunérons toutes les -->
        <!-- collaborations. Si votre projet nous intéresse, nous réfléchirons -->
        <!-- ensemble à la manière de le mener à bien, car Médor travaille toujours -->
        <!-- en équipe pluridisciplinaire.</p> -->

        <!-- <p class="intro-collaborate">Vous avez un projet précis à nous -->
        <!-- proposer :</p> -->

        <!-- <p class="intro-collaborate">Vous êtes journaliste, dessinateur, -->
        <!-- photographe… et vous voulez traiter un sujet d’enquête, de récit ou de -->
        <!-- portrait pour Médor ? Et avec Médor ?</p> -->

        <!-- <p class="intro-collaborate">Remplissez au mieux le formulaire afin que -->
        <!-- l’on puisse voir où vous en êtes dans la réflexion sur votre sujet.</p> -->

        <!-- <p class="intro-collaborate">Quel que soit le support médiatique que -->
        <!-- vous choisissez (texte, photo, BD, roman-photo, mots croisés…), -->
        <!-- visitez notre <a href="/">site web</a> pour comprendre qui nous sommes -->
        <!-- et ce que nous voulons publier. Il va de soi que Médor s’engage à -->
        <!-- respecter la confidentialité de cette proposition et à n’en faire aucun -->
        <!-- usage, aucune communication sans l’autorisation de l’auteur.</p> -->

        <!-- <p class="intro-collaborate">Les réunions de rédaction se déroulent -->
        <!-- chaque mois.</p> -->

        <!-- <p class="intro-collaborate">Si vous avez simplement une information, une idée, une suspicion à -->
        <!-- partager avec nous, en pensant que cela pourrait déboucher sur un sujet -->
        <!-- pour Médor, alors <a href="{% url 'article-proposal-simple' %}">remplissez notre autre formulaire (simplifié)</a></p> -->

        {% if form.errors %}
        <p style="color: red;">Veuillez corriger les erreurs ci-dessous</p>
    {% endif %}

    </div>

    <form style="margin:auto 15% !important;" action="" method="post">
        {% csrf_token %}
        <div class="contact-wrapper">
            <div class="form-wrapper">
                <div class="form-chunk">
                    <div class="box table">
                        <div class="required table-row">
                            {{ form.name.label_tag }}
                            <div class="table-cell">
                            {{ form.name }}
                            {{ form.name.errors }}
                            {{ form.name.field.help_text }}
                            </div>
                        </div>

                        <div class="required table-row">
                            {{ form.email.label_tag }}
                            <div class="table-cell">
                            {{ form.email }}
                            {{ form.email.errors }}
                            {{ form.email.field.help_text }}
                            </div>
                        </div>

                        <div class="table-row">
                            {{ form.phone.label_tag }}
                            <div class="table-cell">
                            {{ form.phone }}
                            {{ form.phone.errors }}
                            {{ form.phone.field.help_text }}
                            </div>
                        </div>

                        <div class="table-row">
                            {{ form.twitter_account.label_tag }}
                            <div class="table-cell">
                            {{ form.twitter_account }}
                            {{ form.twitter_account.errors }}
                            {{ form.twitter_account.field.help_text }}
                            </div>
                        </div>
                    </div>
                </div>        
                <div class="form-chunk">
                    <div class="box table">
                        <div class="required table-row">
                            {{ form.address.label_tag }}
                            <div class="table-cell">
                            {{ form.address }}
                            {{ form.address.errors }}
                            {{ form.address.field.help_text }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>   
        </div> 
        <div class="required" style="padding:0 30px; text-align:left;">
            {{ form.subject_title.label_tag }}
            <div class="help-text">
            {{ form.subject_title.help_text }}
            </div>
            <div class="article-proposal-field">
            {{ form.subject_title }}
            {{ form.subject_title.errors }}
            </div>
        </div>
        <div class="required" style="padding:0 30px; text-align:left;">
            {{ form.body.label_tag }}
            <div class="help-text">
            {{ form.body.help_text }}
            </div>
            <div class="article-proposal-field">
            {{ form.body }}
            {{ form.body.errors }}
            </div>
        </div>
        <div id="confirm">
            <p class="submit-collaborate">Médor vous fait la bise et vous remercie bien.</p>

            <input style="margin-top:15px" type="submit" value="Envoyer" />
        </div>
    </form>
{% endblock %}

collaborate/templates/collaborate/article_proposal_simple.html
{% extends "subscribe/base_forms.html" %}
{% load i18n collaborate_tags %}

{% block id %}collaborating{% endblock %}

{% block content %}
    <div id="steps">
        <div class="active" style="margin:auto 15% !important; margin-top:15px !important;">Suggérer un sujet</div>

        <p class="intro-collaborate">Si vous avez une idée, une info ou une
        piste à nous suggérer, merci de remplir ce formulaire confidentiel.
        Expliquez-nous le plus clairement possible ce dont il s’agit et en quoi
        le sujet vous concerne éventuellement. Nous ne pouvons malheureusement
        pas répondre à tout le monde mais nous vous lirons avec intérêt.
        Merci !</p>

        {% if form.errors %}
        <p style="color: red;">Veuillez corriger les erreurs ci-dessous</p>
    {% endif %}

    </div>

    <form style="margin:auto 15% !important;" action="" method="post">
        {% csrf_token %}
        <div class="contact-wrapper">
            <div class="form-wrapper">
                <div class="form-chunk">
                    <div class="box table">
                        <div class="required table-row">
                            {{ form.name.label_tag }}
                            <div class="table-cell">
                            {{ form.name }}
                            {{ form.name.errors }}
                            {{ form.name.field.help_text }}
                            </div>
                        </div>

                        <div class="required table-row">
                            {{ form.email.label_tag }}
                            <div class="table-cell">
                            {{ form.email }}
                            {{ form.email.errors }}
                            {{ form.email.field.help_text }}
                            </div>
                        </div>

                        <div class="table-row">
                            {{ form.phone.label_tag }}
                            <div class="table-cell">
                            {{ form.phone }}
                            {{ form.phone.errors }}
                            {{ form.phone.field.help_text }}
                            </div>
                        </div>
                    </div>
                </div>        
                <div class="form-chunk">
                    <div class="box table">
                        <div class="required table-row">
                            {{ form.address.label_tag }}
                            <div class="table-cell">
                            {{ form.address }}
                            {{ form.address.errors }}
                            {{ form.address.field.help_text }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>   
        </div> 
        <div class="required" style="padding:0 30px; text-align:left;">
            {{ form.subject_title.label_tag }}
            <div class="help-text">
            {{ form.subject_title.help_text }}
            </div>
            <div class="article-proposal-field">
            {{ form.subject_title }}
            {{ form.subject_title.errors }}
            </div>
        </div>
        <div class="required" style="padding:0 30px; text-align:left;">
            {{ form.body.label_tag }}
            <div class="help-text">
            Présentez ici vos idées ou votre proposition
            </div>
            <div class="article-proposal-field">
            {{ form.body }}
            {{ form.body.errors }}
            </div>
        </div>
        <div id="confirm">
            <!-- <p class="submit-collaborate">Vous avez répondu aux questions -->
            <!-- ci-dessus ? Médor s’engage à vous donner une réponse prochainement -->
            <!-- et vous remercie chaleureusement pour la confiance que vous lui -->
            <!-- accordez ! Meilleures salutations.</p> -->

            <input style="margin-top:15px" type="submit" value="Envoyer" />
        </div>
    </form>
{% endblock %}

collaborate/templates/collaborate/article_proposal_thanks.html
{% extends "subscribe/base_forms.html" %}
{% load i18n collaborate_tags %}

{% block id %}collaborating{% endblock %}

{% block content %}
    <div id="steps">
        <div class="active" style="margin:auto 15% !important; margin-top:15px !important;">Collaboration</div>
        <p class="intro-collaborate">
        Merci pour votre proposition. Un e-mail de confirmation devrait vous
        parvenir très prochainement. Par mesure de confidentialité les données
        transmises à l’aide de ce formulaire n’y figureront pas.<p>
        </p>

        <p class="intro-collaborate">L’équipe de Médor<br />
        <a href="https://medor.coop">www.medor.coop</a> — <a
           href="http://www.facebook.com/medormag">www.facebook.com/medormag</a></p>
        </div>
    </div>
{% endblock %}

collaborate/templates/collaborate/articleproposal_detail.html
{% extends "base3.html" %}


{% load compress sekizai_tags %}


{% block content %}
{% addtoblock "css" %}
{% if debug %}
<!-- This is the client-side way to compile less and an ok choice for local dev -->
<link rel="stylesheet/less" type="text/css" media="all" href="{{ STATIC_URL }}less/articleproposal_list.less" />
{% else %}
{% compress css %}
<!-- This is the nifty django-compressor way to compile your less files in css -->
<link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}less/articleproposal_list.less" charset="utf-8">
{% endcompress %}
{% endif %}
{% endaddtoblock %}


<main id="main-content" class="wrapper main-section">
    <article>
        <header>
            <h1>{{ object.subject_title }} {% if object.is_urgent %}(urgent){% endif %}</h1>
            <dl>
                <dt>Date de création</dt>
                <dd>{{ object.creation_date }}</dd>
                <dt>Nom</dt>
                <dd>{{ object.name }}</dd>
                <dt>Courriel</dt>
                <dd>{{ object.email }}</dd>
                <dt>Téléphone</dt>
                <dd>{{ object.phone }}</dd>
                <dt>Compte Twitter</dt>
                <dd>{{ object.twitter_account|default:"—" }}</dd>
                <dt>Adresse</dt>
                <dd>{{ object.address }}</dd>
            </dl>
        </header>

        <h2>Résumé (prévisionnel)</h2>
        {{ object.abstract }}

        <h2>Rubrique concernée (a priori)</h2>
        {{ object.get_section_display }}

        {{ object.body_as_html|safe }}
    </article>
</main>

{% endblock %}

collaborate/templates/collaborate/articleproposal_list.html
{% extends "base3.html" %}


{% load compress sekizai_tags %}


{% block content %}
{% addtoblock "css" %}
{% if debug %}
<!-- This is the client-side way to compile less and an ok choice for local dev -->
<link rel="stylesheet/less" type="text/css" media="all" href="{{ STATIC_URL }}less/articleproposal_list.less" />
{% else %}
{% compress css %}
<!-- This is the nifty django-compressor way to compile your less files in css -->
<link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}less/articleproposal_list.less" charset="utf-8">
{% endcompress %}
{% endif %}
{% endaddtoblock %}


<main id="main-content" class="wrapper main-section">
    <ol>
    {% for obj in object_list %}
    <li>{{ obj.creation_date }} — <a href="{{ obj.get_absolute_url }}">{{ obj }}</a></li>
    {% endfor %}
    </ol>
</main>

{% endblock %}